name: Laravel CI

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, mysqlnd, sqlite3

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      # Uncomment if you want to run migrations automatically
      # - name: Run migrations
      #   run: php artisan migrate --force

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -avz --delete --exclude='.env' --exclude='storage/' . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/UmeAcademy-Laravel

